<?php

namespace Database\Seeders;

use App\Models\Machine;
use Illuminate\Database\Seeder;

class MachineSeeder extends Seeder
{
    /**
     * The full gym exercise / equipment library, transcribed from the club's
     * exercise catalogue. Each entry maps the exercise name to the muscle group
     * shown for it in the catalogue. Cardio exercises are intentionally excluded.
     *
     * @var array<string, string>
     */
    private array $exercises = [
        // A
        '21s Bicep Curl' => 'Biceps',
        'Ab Scissors' => 'Abdominals',
        'Ab Wheel' => 'Abdominals',
        'Arnold Press (Dumbbell)' => 'Shoulders',
        'Around The World' => 'Chest',
        'Assisted Pistol Squats' => 'Quadriceps',
        // B
        'Back Extension (Hyperextension)' => 'Lower Back',
        'Back Extension (Machine)' => 'Lower Back',
        'Back Extension (Weighted Hyperextension)' => 'Lower Back',
        'Ball Slams' => 'Full Body',
        'Band Pullaparts' => 'Shoulders',
        'Behind the Back Bicep Wrist Curl (Barbell)' => 'Forearms',
        'Behind the Back Curl (Cable)' => 'Biceps',
        'Belt Squat (Machine)' => 'Quadriceps',
        'Bench Dip' => 'Triceps',
        'Bench Press - Close Grip (Barbell)' => 'Triceps',
        'Bench Press - Wide Grip (Barbell)' => 'Chest',
        'Bench Press (Barbell)' => 'Chest',
        'Bench Press (Cable)' => 'Chest',
        'Bench Press (Dumbbell)' => 'Chest',
        'Bench Press (Smith Machine)' => 'Chest',
        'Bent Over Row (Band)' => 'Upper Back',
        'Bent Over Row (Barbell)' => 'Upper Back',
        'Bent Over Row (Dumbbell)' => 'Upper Back',
        'Bicep Curl (Barbell)' => 'Biceps',
        'Bicep Curl (Cable)' => 'Biceps',
        'Bicep Curl (Dumbbell)' => 'Biceps',
        'Bicep Curl (Machine)' => 'Biceps',
        'Bicep Curl (Suspension)' => 'Biceps',
        'Bicycle Crunch' => 'Abdominals',
        'Bicycle Crunch Raised Legs' => 'Abdominals',
        'Bird Dog' => 'Glutes',
        'Box Jump' => 'Quadriceps',
        'Box Squat (Barbell)' => 'Quadriceps',
        'Bulgarian Split Squat' => 'Quadriceps',
        'Burpee' => 'Full Body',
        'Burpee Broad Jumps' => 'Full Body',
        'Burpee Over the Bar' => 'Full Body',
        'Butterfly (Pec Deck)' => 'Chest',
        // C
        'Cable Core Pallof Press' => 'Abdominals',
        'Cable Crunch' => 'Abdominals',
        'Cable Fly Crossovers' => 'Chest',
        'Cable Pull Through' => 'Glutes',
        'Cable Twist (Down to up)' => 'Abdominals',
        'Cable Twist (Up to down)' => 'Abdominals',
        'Calf Extension (Machine)' => 'Calves',
        'Calf Press (Machine)' => 'Calves',
        'Chest Dip' => 'Chest',
        'Chest Dip (Assisted)' => 'Chest',
        'Chest Dip (Weighted)' => 'Chest',
        'Chest Fly (Band)' => 'Chest',
        'Chest Fly (Dumbbell)' => 'Chest',
        'Chest Fly (Machine)' => 'Chest',
        'Chest Fly (Suspension)' => 'Chest',
        'Chest Press (Band)' => 'Chest',
        'Chest Press (Machine)' => 'Chest',
        'Chest Supported Incline Row (Dumbbell)' => 'Upper Back',
        'Chest Supported Reverse Fly (Dumbbell)' => 'Shoulders',
        'Chest Supported Y Raise (Dumbbell)' => 'Shoulders',
        'Chin Up' => 'Lats',
        'Chin Up (Assisted)' => 'Lats',
        'Chin Up (Weighted)' => 'Lats',
        'Clamshell' => 'Glutes',
        'Clap Push Ups' => 'Chest',
        'Clean' => 'Full Body',
        'Clean and Jerk' => 'Full Body',
        'Clean and Press' => 'Full Body',
        'Clean Pull' => 'Full Body',
        'Concentration Curl' => 'Biceps',
        'Cross Body Hammer Curl' => 'Biceps',
        'Crunch' => 'Abdominals',
        'Crunch (Machine)' => 'Abdominals',
        'Crunch (Weighted)' => 'Abdominals',
        'Curtsy Lunge (Dumbbell)' => 'Quadriceps',
        // D
        'Dead Bug' => 'Abdominals',
        'Dead Hang' => 'Upper Back',
        'Deadlift (Band)' => 'Glutes',
        'Deadlift (Barbell)' => 'Glutes',
        'Deadlift (Dumbbell)' => 'Glutes',
        'Deadlift (Smith Machine)' => 'Glutes',
        'Deadlift (Trap bar)' => 'Glutes',
        'Deadlift High Pull' => 'Full Body',
        'Decline Bench Press (Barbell)' => 'Chest',
        'Decline Bench Press (Dumbbell)' => 'Chest',
        'Decline Bench Press (Machine)' => 'Chest',
        'Decline Bench Press (Smith Machine)' => 'Chest',
        'Decline Chest Fly (Dumbbell)' => 'Chest',
        'Decline Crunch' => 'Abdominals',
        'Decline Crunch (Weighted)' => 'Abdominals',
        'Decline Push Up' => 'Chest',
        'Diamond Push Up' => 'Triceps',
        'Downward Dog' => 'Full Body',
        'Drag Curl' => 'Biceps',
        'Dragon Flag' => 'Abdominals',
        'Dragonfly' => 'Abdominals',
        'Dumbbell Row' => 'Lats',
        'Dumbbell Snatch' => 'Full Body',
        'Dumbbell Squeeze Press' => 'Chest',
        'Dumbbell Step Up' => 'Quadriceps',
        // E
        'Elbow to Knee' => 'Abdominals',
        'EZ Bar Biceps Curl' => 'Biceps',
        // F
        'Face Pull' => 'Shoulders',
        'Farmers Walk' => 'Full Body',
        'Feet Up Bench Press (Barbell)' => 'Chest',
        'Fire Hydrants' => 'Glutes',
        'Floor Press (Barbell)' => 'Chest',
        'Floor Press (Dumbbell)' => 'Chest',
        'Floor Triceps Dip' => 'Triceps',
        'Flutter Kicks' => 'Abdominals',
        'Frog Jumps' => 'Quadriceps',
        'Frog Pumps (Dumbbell)' => 'Glutes',
        'Front Lever Hold' => 'Full Body',
        'Front Lever Raise' => 'Full Body',
        'Front Raise (Band)' => 'Shoulders',
        'Front Raise (Barbell)' => 'Shoulders',
        'Front Raise (Cable)' => 'Shoulders',
        'Front Raise (Dumbbell)' => 'Shoulders',
        'Front Raise (Suspension)' => 'Shoulders',
        'Front Squat' => 'Quadriceps',
        'Full Squat' => 'Quadriceps',
        // G
        'Glute Bridge' => 'Glutes',
        'Glute Ham Raise' => 'Hamstrings',
        'Glute Kickback (Machine)' => 'Glutes',
        'Glute Kickback on Floor' => 'Glutes',
        'Goblet Squat' => 'Quadriceps',
        'Good Morning (Barbell)' => 'Hamstrings',
        'Gorilla Row (Kettlebell)' => 'Upper Back',
        // H
        'Hack Squat' => 'Quadriceps',
        'Hack Squat (Machine)' => 'Quadriceps',
        'Hammer Curl (Band)' => 'Biceps',
        'Hammer Curl (Cable)' => 'Biceps',
        'Hammer Curl (Dumbbell)' => 'Biceps',
        'Handstand Hold' => 'Full Body',
        'Handstand Push Up' => 'Shoulders',
        'Hang Clean' => 'Full Body',
        'Hang Snatch' => 'Full Body',
        'Hanging Knee Raise' => 'Abdominals',
        'Hanging Leg Raise' => 'Abdominals',
        'Heel Taps' => 'Abdominals',
        'Hex Press (Dumbbell)' => 'Chest',
        'High Knee Skips' => 'Full Body',
        'High Knees' => 'Full Body',
        'Hip Abduction (Machine)' => 'Abductors',
        'Hip Adduction (Machine)' => 'Adductors',
        'Hip Thrust' => 'Glutes',
        'Hip Thrust (Barbell)' => 'Glutes',
        'Hip Thrust (Machine)' => 'Glutes',
        'Hip Thrust (Smith Machine)' => 'Glutes',
        'Hollow Rock' => 'Abdominals',
        // I
        'Incline Bench Press (Barbell)' => 'Chest',
        'Incline Bench Press (Dumbbell)' => 'Chest',
        'Incline Bench Press (Smith Machine)' => 'Chest',
        'Incline Chest Fly (Dumbbell)' => 'Chest',
        'Incline Chest Press (Machine)' => 'Chest',
        'Incline Push Ups' => 'Chest',
        'Inverted Row' => 'Upper Back',
        'Iso-Lateral Chest Press (Machine)' => 'Chest',
        'Iso-Lateral High Row (Machine)' => 'Lats',
        'Iso-Lateral Low Row' => 'Upper Back',
        'Iso-Lateral Row (Machine)' => 'Upper Back',
        // J
        'Jack Knife (Suspension)' => 'Abdominals',
        'Jackknife Sit Up' => 'Abdominals',
        'JM Press (Barbell)' => 'Triceps',
        'Jump Shrug' => 'Full Body',
        'Jump Squat' => 'Quadriceps',
        'Jumping Jack' => 'Full Body',
        'Jumping Lunge' => 'Quadriceps',
        // K
        'Kettlebell Around the World' => 'Shoulders',
        'Kettlebell Clean' => 'Full Body',
        'Kettlebell Curl' => 'Biceps',
        'Kettlebell Halo' => 'Shoulders',
        'Kettlebell High Pull' => 'Full Body',
        'Kettlebell Shoulder Press' => 'Shoulders',
        'Kettlebell Snatch' => 'Full Body',
        'Kettlebell Swing' => 'Full Body',
        'Kettlebell Turkish Get Up' => 'Full Body',
        'Kipping Pull Up' => 'Lats',
        'Knee Raise Parallel Bars' => 'Abdominals',
        'Kneeling Pulldown (band)' => 'Lats',
        'Kneeling Push Up' => 'Chest',
        // L
        'L-Sit Hold' => 'Abdominals',
        'Landmine 180' => 'Abdominals',
        'Landmine Row' => 'Upper Back',
        'Landmine Squat and Press' => 'Full Body',
        'Lat Pulldown (Band)' => 'Lats',
        'Lat Pulldown (Cable)' => 'Lats',
        'Lat Pulldown (Machine)' => 'Lats',
        'Lateral Band Walks' => 'Glutes',
        'Lateral Box Jump' => 'Quadriceps',
        'Lateral Leg Raises' => 'Glutes',
        'Lateral Raise (Band)' => 'Shoulders',
        'Lateral Raise (Cable)' => 'Shoulders',
        'Lateral Raise (Dumbbell)' => 'Shoulders',
        'Lateral Raise (Machine)' => 'Shoulders',
        'Lateral Squat' => 'Quadriceps',
        'Leg Extension (Machine)' => 'Quadriceps',
        'Leg Press (Machine)' => 'Quadriceps',
        'Leg Raise Parallel Bars' => 'Abdominals',
        'Low Cable Fly Crossovers' => 'Chest',
        'Low Row (Suspension)' => 'Upper Back',
        'Lunge' => 'Quadriceps',
        'Lunge (Barbell)' => 'Quadriceps',
        'Lunge (Dumbbell)' => 'Quadriceps',
        'Lying Knee Raise' => 'Abdominals',
        'Lying Leg Curl (Machine)' => 'Hamstrings',
        'Lying Leg Raise' => 'Abdominals',
        'Lying Neck Curls' => 'Neck',
        'Lying Neck Curls (Weighted)' => 'Neck',
        'Lying Neck Extension' => 'Neck',
        'Lying Neck Extension (Weighted)' => 'Neck',
        // M
        'Meadows Rows (Barbell)' => 'Upper Back',
        'Mountain Climber' => 'Full Body',
        'Muscle Up' => 'Full Body',
        // N
        'Negative Pull Up' => 'Lats',
        'Nordic Hamstrings Curls' => 'Hamstrings',
        // O
        'Oblique Crunch' => 'Abdominals',
        'One Arm Push Up' => 'Chest',
        'Overhead Curl (Cable)' => 'Biceps',
        'Overhead Dumbbell Lunge' => 'Quadriceps',
        'Overhead Plate Raise' => 'Shoulders',
        'Overhead Press (Barbell)' => 'Shoulders',
        'Overhead Press (Dumbbell)' => 'Shoulders',
        'Overhead Press (Smith Machine)' => 'Shoulders',
        'Overhead Squat' => 'Full Body',
        'Overhead Triceps Extension (Cable)' => 'Triceps',
        // P
        'Partial Glute Bridge (Barbell)' => 'Glutes',
        'Pause Squat (Barbell)' => 'Quadriceps',
        'Pendlay Row (Barbell)' => 'Upper Back',
        'Pendulum Squat (Machine)' => 'Quadriceps',
        'Pike Pushup' => 'Shoulders',
        'Pilates' => 'Full Body',
        'Pinwheel Curl (Dumbbell)' => 'Biceps',
        'Pistol Squat' => 'Quadriceps',
        'Plank' => 'Abdominals',
        'Plank Pushup' => 'Chest',
        'Plate Curl' => 'Biceps',
        'Plate Front Raise' => 'Shoulders',
        'Plate Press' => 'Chest',
        'Plate Squeeze (Svend Press)' => 'Chest',
        'Power Clean' => 'Full Body',
        'Power Snatch' => 'Full Body',
        'Preacher Curl (Barbell)' => 'Biceps',
        'Preacher Curl (Dumbbell)' => 'Biceps',
        'Preacher Curl (Machine)' => 'Biceps',
        'Press Under' => 'Full Body',
        'Pull Up' => 'Lats',
        'Pull Up (Assisted)' => 'Lats',
        'Pull Up (Band)' => 'Lats',
        'Pull Up (Weighted)' => 'Lats',
        'Pullover (Dumbbell)' => 'Lats',
        'Pullover (Machine)' => 'Lats',
        'Push Press' => 'Shoulders',
        'Push Up' => 'Chest',
        'Push Up - Close Grip' => 'Chest',
        'Push Up (Weighted)' => 'Chest',
        // R
        'Rack Pull' => 'Upper Back',
        'Rear Delt Reverse Fly (Cable)' => 'Shoulders',
        'Rear Delt Reverse Fly (Dumbbell)' => 'Shoulders',
        'Rear Delt Reverse Fly (Machine)' => 'Shoulders',
        'Rear Kick (Machine)' => 'Glutes',
        'Renegade Row (Dumbbell)' => 'Upper Back',
        'Reverse Crunch' => 'Abdominals',
        'Reverse Curl (Barbell)' => 'Biceps',
        'Reverse Curl (Cable)' => 'Biceps',
        'Reverse Curl (Dumbbell)' => 'Biceps',
        'Reverse Fly Single Arm (Cable)' => 'Shoulders',
        'Reverse Grip Concentration Curl' => 'Biceps',
        'Reverse Grip Lat Pulldown (Cable)' => 'Lats',
        'Reverse Hyperextension' => 'Glutes',
        'Reverse Lunge' => 'Quadriceps',
        'Reverse Lunge (Barbell)' => 'Quadriceps',
        'Reverse Lunge (Dumbbell)' => 'Quadriceps',
        'Reverse Plank' => 'Abdominals',
        'Ring Dips' => 'Chest',
        'Ring Pull Up' => 'Lats',
        'Ring Push Up' => 'Chest',
        'Romanian Deadlift (Barbell)' => 'Hamstrings',
        'Romanian Deadlift (Dumbbell)' => 'Hamstrings',
        'Rope Cable Curl' => 'Biceps',
        'Rope Straight Arm Pulldown' => 'Lats',
        'Russian Twist (Bodyweight)' => 'Abdominals',
        'Russian Twist (Weighted)' => 'Abdominals',
        // S
        'Scapular Pull Ups' => 'Upper Back',
        'Seated Cable Row - Bar Grip' => 'Upper Back',
        'Seated Cable Row - Bar Wide Grip' => 'Upper Back',
        'Seated Cable Row - V Grip (Cable)' => 'Upper Back',
        'Seated Calf Raise' => 'Calves',
        'Seated Chest Flys (Cable)' => 'Chest',
        'Seated Dip Machine' => 'Triceps',
        'Seated Incline Curl (Dumbbell)' => 'Biceps',
        'Seated Lateral Raise (Dumbbell)' => 'Shoulders',
        'Seated Leg Curl (Machine)' => 'Hamstrings',
        'Seated Overhead Press (Barbell)' => 'Shoulders',
        'Seated Overhead Press (Dumbbell)' => 'Shoulders',
        'Seated Palms Up Wrist Curl' => 'Forearms',
        'Seated Row (Machine)' => 'Upper Back',
        'Seated Shoulder Press (Machine)' => 'Shoulders',
        'Seated Triceps Press' => 'Triceps',
        'Seated Wrist Extension (Barbell)' => 'Forearms',
        'Shoulder Press (Dumbbell)' => 'Shoulders',
        'Shoulder Press (Machine Plates)' => 'Shoulders',
        'Shoulder Taps' => 'Shoulders',
        'Shrug (Barbell)' => 'Traps',
        'Shrug (Cable)' => 'Traps',
        'Shrug (Dumbbell)' => 'Traps',
        'Shrug (Machine)' => 'Traps',
        'Shrug (Smith Machine)' => 'Traps',
        'Side Bend' => 'Abdominals',
        'Side Bend (Dumbbell)' => 'Abdominals',
        'Side Plank' => 'Abdominals',
        'Single Arm Cable Crossover' => 'Chest',
        'Single Arm Cable Row' => 'Upper Back',
        'Single Arm Curl (Cable)' => 'Biceps',
        'Single Arm Landmine Press (Barbell)' => 'Shoulders',
        'Single Arm Lat Pulldown' => 'Lats',
        'Single Arm Lateral Raise (Cable)' => 'Shoulders',
        'Single Arm Tricep Extension (Dumbbell)' => 'Triceps',
        'Single Arm Triceps Pushdown (Cable)' => 'Triceps',
        'Single Leg Extensions' => 'Quadriceps',
        'Single Leg Glute Bridge' => 'Glutes',
        'Single Leg Hip Thrust' => 'Glutes',
        'Single Leg Hip Thrust (Dumbbell)' => 'Glutes',
        'Single Leg Press (Machine)' => 'Quadriceps',
        'Single Leg Romanian Deadlift' => 'Hamstrings',
        'Single Leg Romanian Deadlift (Barbell)' => 'Hamstrings',
        'Single Leg Romanian Deadlift (Dumbbell)' => 'Hamstrings',
        'Single Leg Standing Calf Raise' => 'Calves',
        'Single Leg Standing Calf Raise (Barbell)' => 'Calves',
        'Single Leg Standing Calf Raise (Dumbbell)' => 'Calves',
        'Single Leg Standing Calf Raise (Machine)' => 'Calves',
        'Sissy Squat (Weighted)' => 'Quadriceps',
        'Sit Up' => 'Abdominals',
        'Sit Up (Weighted)' => 'Abdominals',
        'Skullcrusher (Barbell)' => 'Triceps',
        'Skullcrusher (Dumbbell)' => 'Triceps',
        'Sled Pull' => 'Full Body',
        'Sled Push' => 'Full Body',
        'Snatch' => 'Full Body',
        'Spider Curl (Barbell)' => 'Biceps',
        'Spider Curl (Dumbbell)' => 'Biceps',
        'Spiderman' => 'Abdominals',
        'Split Jerk' => 'Full Body',
        'Split Squat (Dumbbell)' => 'Quadriceps',
        'Squat (Band)' => 'Quadriceps',
        'Squat (Barbell)' => 'Quadriceps',
        'Squat (Bodyweight)' => 'Quadriceps',
        'Squat (Dumbbell)' => 'Quadriceps',
        'Squat (Machine)' => 'Quadriceps',
        'Squat (Smith Machine)' => 'Quadriceps',
        'Squat (Suspension)' => 'Quadriceps',
        'Squat Row' => 'Full Body',
        'Standing Cable Glute Kickbacks' => 'Glutes',
        'Standing Calf Raise' => 'Calves',
        'Standing Calf Raise (Barbell)' => 'Calves',
        'Standing Calf Raise (Dumbbell)' => 'Calves',
        'Standing Calf Raise (Machine)' => 'Calves',
        'Standing Calf Raise (Smith)' => 'Calves',
        'Standing Leg Curls' => 'Hamstrings',
        'Standing Military Press (Barbell)' => 'Shoulders',
        'Step Up' => 'Quadriceps',
        'Sternum Pull up (Gironda)' => 'Lats',
        'Straight Arm Lat Pulldown (Cable)' => 'Lats',
        'Straight Leg Deadlift' => 'Hamstrings',
        'Stretching' => 'Other',
        'Sumo Deadlift' => 'Glutes',
        'Sumo Squat' => 'Quadriceps',
        'Sumo Squat (Barbell)' => 'Quadriceps',
        'Sumo Squat (Dumbbell)' => 'Quadriceps',
        'Superman' => 'Lower Back',
        // T
        'T Bar Row' => 'Upper Back',
        'Thruster (Barbell)' => 'Full Body',
        'Thruster (Kettlebell)' => 'Full Body',
        'Toe Touch' => 'Abdominals',
        'Torso Rotation' => 'Abdominals',
        'Triceps Dip' => 'Triceps',
        'Triceps Dip (Assisted)' => 'Triceps',
        'Triceps Dip (Weighted)' => 'Triceps',
        'Triceps Extension (Barbell)' => 'Triceps',
        'Triceps Extension (Cable)' => 'Triceps',
        'Triceps Extension (Suspension)' => 'Triceps',
        'Triceps Kickback (Cable)' => 'Triceps',
        'Triceps Kickback (Dumbbell)' => 'Triceps',
        'Triceps Pressdown' => 'Triceps',
        'Triceps Pushdown' => 'Triceps',
        'Triceps Rope Pushdown' => 'Triceps',
        // U
        'Upright Row (Barbell)' => 'Shoulders',
        'Upright Row (Cable)' => 'Shoulders',
        'Upright Row (Dumbbell)' => 'Shoulders',
        // V
        'V Up' => 'Abdominals',
        'Vertical Traction (Machine)' => 'Lats',
        // W
        'Waiter Curl (Dumbbell)' => 'Biceps',
        'Walking Lunge' => 'Quadriceps',
        'Walking Lunge (Dumbbell)' => 'Quadriceps',
        'Walking Lunge (Sandbag)' => 'Quadriceps',
        'Wall Ball' => 'Full Body',
        'Wall Sit' => 'Quadriceps',
        'Warm Up' => 'Full Body',
        'Wide Pull Up' => 'Lats',
        'Wide-Elbow Triceps Press (Dumbbell)' => 'Triceps',
        'Wrist Roller' => 'Forearms',
        // Y
        'Yoga' => 'Full Body',
        // Z
        'Zercher Squat' => 'Quadriceps',
        'Zottman Curl (Dumbbell)' => 'Biceps',
    ];

    /**
     * Maps a fine-grained muscle group to the coarse category used elsewhere
     * in the app (chest | back | shoulders | arms | legs | core | full_body).
     *
     * @var array<string, string>
     */
    private array $categoryMap = [
        'Chest' => 'chest',
        'Upper Back' => 'back',
        'Lats' => 'back',
        'Lower Back' => 'back',
        'Traps' => 'back',
        'Shoulders' => 'shoulders',
        'Neck' => 'shoulders',
        'Biceps' => 'arms',
        'Triceps' => 'arms',
        'Forearms' => 'arms',
        'Quadriceps' => 'legs',
        'Hamstrings' => 'legs',
        'Calves' => 'legs',
        'Glutes' => 'legs',
        'Abductors' => 'legs',
        'Adductors' => 'legs',
        'Abdominals' => 'core',
        'Full Body' => 'full_body',
        'Other' => 'full_body',
    ];

    public function run(): void
    {
        foreach ($this->exercises as $name => $muscleGroup) {
            Machine::updateOrCreate(
                ['name' => $name],
                [
                    'name' => $name,
                    'muscle_group' => $muscleGroup,
                    'category' => $this->categoryMap[$muscleGroup] ?? 'full_body',
                    'brand' => 'Shua Fitness',
                ],
            );
        }
    }
}
